### ISSUE TITLE
how to add jar to Redhat single sign-on 7.6

### ISSUE THREAD

**Issue by awsmaythem** [sventorben/keycloak-restrict-client-auth#112]
Hello 
I have installed redhat single sign-on 7.6 base on keycloak 18.0.0
i cant find the directory:
<sub>
/opt/jboss/keycloak/providers
</sub>
when i added the jar file in:
<sub>
/opt/eap/standalone/deployments/
</sub>
it added but empty (access provider)
can you help me?
so i can select (access provider) in action>config
![Screenshot_20](https://user-images.githubusercontent.com/85623714/196511085-dbe4ecd7-e5e4-48c0-97c8-e43f49505705.png)
![Screenshot_21](https://user-images.githubusercontent.com/85623714/196511080-18427fac-68a9-4bca-8145-353d2c8f95c2.png)

**Comment by sventorben** [comment]
Hello @awsmaythem,

I do not have access to RH SSO version so that I cannot test this. In general, you need to copy the jar to `KEYCLOAK_HOME/providers` where `KEYCLOAK_HOME` is the root folder of your Keycloak installation. It is possible that the folder does not exist and you have to create it.

Maybe #24 may help.

Regards
Sven-Torben

**Comment by awsmaythem** [comment]
no i created a directory it's still the same
do you want access to RH SSO so you can check?

**Comment by sventorben** [comment]
Can you please execute the following CLI command and post the result here?

```
/subsystem=keycloak-server:read-attribute(name=providers)
```

**Comment by awsmaythem** [comment]
```
[standalone@localhost:9990 /] /subsystem=keycloak-server:read-attribute(name=providers)
/subsystem=keycloak-server:read-attribute(name=providers)
{
    "outcome" => "success",
    "result" => [expression "classpath:${jboss.home.dir}/providers/*"]
}
[standalone@localhost:9990 /]
```
this is the result

**Comment by sventorben** [comment]
Sorry, I forgot to resolve expression. Can you try again with `/subsystem=keycloak-server:read-attribute(name=providers, resolve-expressions=true)`, please. 
The folder shown in the result is where you should copy the jar file to. Make sure it is readable.

**Comment by awsmaythem** [comment]
```
[standalone@localhost:9990 /] /subsystem=keycloak-server:read-attribute(name=providers, resolve-expressions=true)
/subsystem=keycloak-server:read-attribute(name=providers, resolve-expressions=true)
{
    "outcome" => "success",
    "result" => ["classpath:/opt/eap/providers/*"]
}
[standalone@localhost:9990 /]
```
this is the result i'll try this

**Comment by awsmaythem** [comment]
it's working now thanks alot 
![Screenshot_22](https://user-images.githubusercontent.com/85623714/196638442-ee99dcd4-af06-4a9a-a44e-855530a875ba.png)
