### ISSUE TITLE
How to make multiple groups and multiple clients restricted-access name

### ISSUE THREAD

**Issue by awsmaythem** [sventorben/keycloak-restrict-client-auth#118]
Hello
how can I make restricted-access multiple clients?
I saw the #92 

but where to put the role
the client or authentication?

I tested 1 client 1 group
example (Zabbix)
in it has a roles called (restricted-access) and in
Groups (group role mappings) (client role) selected (restricted-access) for the Zabbix client
it's working but how to rename each client have different names like
(zabbix01.restricted-access)
(kibana03.restricted-access)

Zabbix01
(roles)=(zabbix01.restricted-access)
and in 
(group role mappings)->(client role) selected (zabbix01.restricted-access) for the (Zabbix01 client)
![Screenshot_36](https://user-images.githubusercontent.com/85623714/198829299-57a75d16-635c-43f2-926a-eb4f6eb8706d.png)
![Screenshot_35](https://user-images.githubusercontent.com/85623714/198829300-6107e979-62a6-4c80-930e-e117fe2d0920.png)

**Comment by sventorben** [comment]
Hello @awsmaythem,

I am not sure if I really understand what you are trying to achieve here.
Do you want roles to have different names per client? That is currently not possible and I do not think I will support this in the future.
The role `restricted-access` must be defined [per client](https://www.keycloak.org/docs/latest/server_admin/#con-client-roles_server_administration_guide). Therefore, the role name is the same for all clients that you want to restrict. The client works like a namespace or "scope" for the role. In #92 I used the notation `<client_name>.<role_name>` (e.g. `zabbix01.restricted-access`) only to distinguish roles from different clients. I did not want to imply that there is a role with that exact name.
If you want to assign roles from multiple clients to the same group, simply switch the client in the dropdown field and assign the roles as needed.

Best regards
Sven-Torben

**Comment by awsmaythem** [comment]
you mean i can set (zabbix01.restricted-access) in roles in client and select a group or user assigen a client role to it (zabbix01.restricted-access)

**Comment by awsmaythem** [comment]
![Screenshot_41](https://user-images.githubusercontent.com/85623714/198886817-efe36924-787f-4c21-93b5-d031645ae813.png)
![Screenshot_39](https://user-images.githubusercontent.com/85623714/198886830-01255ff0-0184-4079-9182-525bd99500df.png)
![Screenshot_40](https://user-images.githubusercontent.com/85623714/198886833-49eff178-622b-4797-bb6f-191ee297a665.png)

**Comment by sventorben** [comment]
You do not need the prefix with the role name. The name must be the same for every client. It has to be `restricted-access`.

For every client that has this role defined, the authenticator will check access permissions.

To allow a user access to multiple clients, you simply need to assign all defined roles (one for every client) to the user.

I currently do not have my notebook with me. I can send some detailed pictures the next days, if that helps.

**Comment by awsmaythem** [comment]
please show some detailed pictures

**Comment by awsmaythem** [comment]
The Problem am having is I have 3 client services (Zabbix and Kibana and ticket system) and have groups like (team zabbix)(team logs)(team ticket)
in (zabbix client) have role (restricted-access) and (team zabbix) but (kibana client) and (team kibana) if it have (restricted-access) in role and group the (team zabbix) can access (kibana client and team kibana) can access zabbix 
i need a way to separate the role on client and group or users...

**Comment by sventorben** [comment]
Sorry for the late reply, I was off for a few days.

### Let's say you have your three clients.

![image](https://user-images.githubusercontent.com/12183470/199464866-b8f359aa-0986-486b-a89e-130c891d417a.png)

### Add a role `restricted-access` to every client. 
![image](https://user-images.githubusercontent.com/12183470/199465222-d16b3228-cfac-4c91-bf9d-dbd98fc185c3.png)

![image](https://user-images.githubusercontent.com/12183470/199465446-2827f195-d109-4e68-8e8f-aa8173599c8d.png)

![image](https://user-images.githubusercontent.com/12183470/199465601-91d2f94a-79e8-4c06-a75b-9975d9d176aa.png)

### With your three groups, you can now assign the roles to your groups as needed.

![image](https://user-images.githubusercontent.com/12183470/199466187-545d7491-f90c-4416-a6e2-4adf374908a4.png)

### Let's take `team logs` as an example. Open the team and assign role:
![image](https://user-images.githubusercontent.com/12183470/199466548-f11fb0ae-be4c-4485-9f2d-f38290e128e7.png)

## As you can see (in the new admin console at least) there are three roles, one per client. 

![image](https://user-images.githubusercontent.com/12183470/199466824-b7b94faa-e0c5-42ed-93d4-327e6b4efd47.png)
![image](https://user-images.githubusercontent.com/12183470/199467079-0969bf7c-4fa7-47ef-ad2e-e616c1e9449c.png)

You can now assign a combination of these roles as needed. 

In the old admin console it is not that intuitive. You will need to switch clients via the dropdown box:

![image](https://user-images.githubusercontent.com/12183470/199467617-4795455a-6b1e-49e2-a1f5-ebe9f9bdbe24.png)

![image](https://user-images.githubusercontent.com/12183470/199467783-ff1415c1-2063-404c-b642-fc6376b7e11d.png)

**Comment by awsmaythem** [comment]
that explained alot thanks alot
