### ISSUE TITLE
[Feature] Support for configuring different role per client

### ISSUE THREAD

**Issue by danifr** [sventorben/keycloak-restrict-client-auth#134]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

Hi,

first of all, thanks a lot for making this SPI, it works very well and it is very easy to set up :)

I was wondering if there is a way I could configure this plugin so I can set a different role per client.

For example in my organization we have GitLab and Slack both protected with Keycloak. Since they both use a pay-per-user license model I only want users with the `slack_user` role to be authorized to use Slack and `role_gitlab` for gitlab.

Is this something currently possible? If not, do you think it can be something that could be added to the current code?

Thank you very much,
Daniel.

**Comment by danifr** [comment]
@sventorben, thanks for your quick answer.

I guess it can be either of them.
Maybe client-level role will be a bit cleaner for my use-case, but I wouldn't mind adding them as realm roles.

Full disclosure, before I was using this SPI https://github.com/thomasdarimont/keycloak-extension-playground/tree/master/auth-require-role-extension but unfortunately I couldn't make it work with the new version of Keycloak (quarkus distro)

Thanks a lot!

**Comment by danifr** [comment]
Sorry for the confusion. I will try to explain my scenario better.

We have 2 different applications protected by Keycloak: GitLab and Slack. They are using 2 different keycloak clients.

Now, of all the users I have in Keycloak I ONLY want the ones that are in the group `slack_users`
to be able to login to Slack and ONLY the ones that are in `gitlab_users` to be able to access GitLab.
The users in `slack_users` and `gitlab_users` are not the same.

My idea is to implement this restriction via "required roles", so in this case the authentication flow for the Gitlab
client will require the specific role (i.e `gitlab_users_role`). This role will be mapped to the members of the `gitlab_users` group.

Likewise for Slack but in this case with the `slack_users` group and `slack_users_role`.

But my understanding is that you can only configure one global role. So if I do:
```spi-restrict-client-auth-access-provider-client-role-client-role-name=gitlab_users_role```

I will be only restring for the `gitlab_users_role`.

I hope this makes better sense. Thank you very much.

**Comment by sventorben** [comment]
I think this extension already supports exactly what you want to achieve. I think there is a misunderstanding regarding the role name that you can configure globally. Can you check if the information in #118 helps.

If not, please let me know and I try to explain in more detail.

**Comment by danifr** [comment]
Indeed https://github.com/sventorben/keycloak-restrict-client-auth/issues/118#issuecomment-1300013191 looks like exactly what I need!

Danke schön Steven-Torben!!!
