### ISSUE TITLE
[Feature] Support a Docker-based release

### ISSUE THREAD

**Issue by craigtracey** [sventorben/keycloak-restrict-client-auth#192]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

There are deployment scenarios where obtaining the `keycloak-restrict-client-auth` JAR from a Docker image is preferable to other means. In particular, when running Keycloak in a Kubernetes environment, an initContainer sidecar may be used to pull this JAR into a shared `providers` directory, thus allowing for runtime modification of the Keycloak Pod's providers.  

This removes the need for an end user to modify/support their own Keycloak container images.

### Describe alternatives you've considered

Alternatives may include using an initContainer to pull the released JAR at runtime. This adds additional possible failure modes (ie. network unavailability).

Users may also support their own custom Keycloak images, but this comes with a significant support overhead.

**Comment by sventorben** [comment]
Hello @craigtracey 

Thanks for the feature request and the PR.

I don't really understand why it would be beneficial to release this extension as a file inside a Docker image. Can you elaborate on the use case a little more, please?

If you need something like that, it seems verify specific to your current deployment environment. It also does not allow to [optimize the Keycloak startup](https://www.keycloak.org/server/configuration#_optimize_the_keycloak_startup) as suggested by the Keycloak project and is not in line with Keycloak's [recommendation to build a custom optimized image](https://www.keycloak.org/server/containers).

I am therefore very unsure whether I would like to offer and maintain a docker-based release of this extension.

Would you mind starting a [discussion](https://github.com/sventorben/keycloak-restrict-client-auth/discussions) and we see if there is a broader need for this?

Best regards
Sven-Torben

**Comment by sventorben** [comment]
Closing this issue due to missing feedback.
