### ISSUE TITLE
[BUG] Cannot find authentication provider implementation with provider ID 'basic-auth'

### ISSUE THREAD

**Issue by JimVanEeden** [sventorben/keycloak-restrict-client-auth#250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've updated Keycloak and this provider to 23.0.6 and 23.0.0 respectively. While everything was running perfectly on Keycloak v21, I cannot figure out why this provider suddenly doesn't work anymore. When logging in on my client, or when going to the `Browser restricted client auth` flow on the admin pages, the below error is thrown. 

```
Cannot find authentication provider implementation with provider ID 'basic-auth'
```

I've spent many hours trying to make sure the .jar file is correctly installed and trying different things to get everything to work. The issue is definitely coming from somewhere in this package because the normal browser auth works fine. Any info would be great appreciated. 

### Version

```markdown
- Keycloak: 23.0.6
- This extension: 23.0.0
```

**Comment by sventorben** [comment]
Can you please check if the extension is correctly installed?
![image](https://github.com/sventorben/keycloak-restrict-client-auth/assets/12183470/4b812c82-9696-421f-b787-c2896d1c0fc4)

**Comment by JimVanEeden** [comment]
<img width="822" alt="image" src="https://github.com/sventorben/keycloak-restrict-client-auth/assets/5991446/b9564810-4e86-45e4-abd2-70cfdf434678">

That seems to work fine

**Comment by sventorben** [comment]
From the stacktrace it does not look like this error is related to my extension.
The error message says that Keycloak cannot find a provider named "basic-auth". There is no provider within this extension with that name. Could it be that additional authenticators are configured within your flow. Are you maybe missing another extension?

Could you export relevant parts of the flow or show me a screenshot of your flow running on version 21.x from before you upgrade to 23?

**Comment by sventorben** [comment]
Closing due to no feedback. Please re-open or comment when additional details are available.
