### ISSUE TITLE
Issue with Browser flow

### ISSUE THREAD

**Issue by christiaanvaken** [sventorben/keycloak-restrict-client-auth#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have created the following form but when I always get Invalid username or password. Can someone tell me what I am doing wrong?

### Expected Behavior

I should get a login form to enter my username and password

### Version

```markdown
Keycloak 24.0.0
```

### Anything else?

![Screenshot 2024-03-05 at 09 41 53](https://github.com/sventorben/keycloak-restrict-client-auth/assets/48440707/9fb63b9e-2d90-4b72-89f3-8ac199e9efe9)

**Comment by sventorben** [comment]
Which version of this extension do you use and what does KC say in the logs?

Are you not seeing a login form at all?

**Comment by christiaanvaken** [comment]
I am using the latest version (24.0.0). I am not seeing a login form at all.

**Comment by sventorben** [comment]
Can you please verify the version (see screenshot)?

![image](https://github.com/sventorben/keycloak-restrict-client-auth/assets/12183470/c8c1807d-f62b-44f1-8f61-5dbed9006e8f)

Do you see an error or warning in the logs?

**Comment by christiaanvaken** [comment]
The version is 24.0.0. The Keycloak logfile shows:
WARN  [org.keycloak.services] (executor-thread-3) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException: Unknown flow provider type

**Comment by sventorben** [comment]
This looks like an issue with your flow to me. What type does your `Login` flow have?
Maybe an export of your realm could help to look it up.

**Comment by christiaanvaken** [comment]
The type is basic-flow.

**Comment by sventorben** [comment]
This seems to be an issue with Keycloak itself and not with this extension.

Please see and track https://github.com/keycloak/keycloak/issues/27548.

**Comment by christiaanvaken** [comment]
So for the time being it is best to downgrade to version 23?

**Comment by sventorben** [comment]
I'd say yes, if you need to create a custom flow.

**Comment by sventorben** [comment]
@christiaanvaken did some further investigations: you can try to toggle the "Flow type" selection once when creating the new flow and explicitly select "basic flow". Then it worked for me.
