### ISSUE TITLE
[BUG] SSO allows bypassing the client restriction

### ISSUE THREAD

**Issue by konradwudkowski** [sventorben/keycloak-restrict-client-auth#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When multiple clients exist, an active keycloak session created by logging in to one client bypasses restrictions set on another client and allows a user to log in

I tried with the "Role-based mode"

If we go to client that has restrictions first it works as expected and user is stopped at keycloak page

### Expected Behavior

I expect that when I logged in to one client and keycloak session is active, when I go to another client that has restricted-access I would NOT be allowed to access

### Steps To Reproduce

1. Create 2 clients, `client1` that has restrictions and `client2` that doesn't
2. Set restrictions such that `user1` cannot log in to `client1` because they don't have the `restricted-access` role for `client1`
3. Log in to `client2` with `user1` - this works fine because there were no restrictions
4. Go to `client1` and keycloak will log you in bypassing the restrictions set by this plugin

### Version

```markdown
- Keycloak: 15.0.2 (wildfly)
- This extension: 15.1.0
```

**Comment by sventorben** [comment]
Hey @konradwudkowski,

thanks for reporting this.
Could you please let me know what your authentication flow looks like?

Regards
@sventorben

**Comment by konradwudkowski** [comment]
It's a "copy of browser" with "Restrict User Authentication on Clients" added at the end and set to required - no further changes

**Comment by konradwudkowski** [comment]
btw. I've just edited Steps to Reproduce as I didn't fully capture the problem before, for clarity I edited as follows:

```
from:
2. Set restrictions such that user1 can log in to client1 because they have the restricted-access role for client1
to:
2. Set restrictions such that `user1` cannot log in to `client1` because they don't have the `restricted-access` role for `client1`
```

**Comment by sventorben** [comment]
In that case I assume that you configured it as an alternative to the `Coockie authenticator`.
Can you please make sure to configure the authenticator as described in the [README.md](https://github.com/sventorben/keycloak-restrict-client-auth#how-to-configure) (see [this picture](https://github.com/sventorben/keycloak-restrict-client-auth/blob/main/docs/images/flow.jpg)).

Alternatively, [this issue](https://github.com/sventorben/keycloak-restrict-client-auth/issues/9#issuecomment-937059969) could serve as a good example for your use case.

Let me know if this works for you, @konradwudkowski. I will try to make the docs more clear in this point.

**Comment by konradwudkowski** [comment]
Thanks @sventorben. It works now as expected when I rearranged the flow as suggested 👍
