### ISSUE TITLE
[BUG] I can't make it work for Client authentication flow

### ISSUE THREAD

**Issue by masalinas** [sventorben/keycloak-restrict-client-auth#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

To beginning thanks for your great extension but I can't make it work for the Client authentication flow with restriction task activated

### Expected Behavior

Test Client authentication flow with restriction task activated

### Steps To Reproduce

**I followed your Browser Restriction sample succesfully, but if I try to replicate the same for Client Authenticactions I obtained some issues.** These are the steps followed by me in this last sample:

1. Start from scratch the last Keycloak docker container version 25.0.2 with the **keycloak-restrict-client-auth** extension inside

2. Create a new realm called **mock**

3. Create a new client inside this realm called **mock** with two client roles: **user** and **restricted-access**

4. Create two users called: **user** and **maintenance**. the **user** has the role **user**, the **maintenance** user has the role **restricted-access**

5. Create a new Authentication Flow called **clients-maintenance** duplicated from **clients** Flow and add a subflow at the end called login and inside it the Step **Restric user authentication on Clients** like this:

<img width="796" alt="image" src="https://github.com/user-attachments/assets/e85beaaf-f0a3-4fb2-8281-085716d00e93">

Configure the step **Restrictive user and authentication of client**s with this data:

<img width="310" alt="image" src="https://github.com/user-attachments/assets/43ecb372-b967-49f4-8be2-a89cc5861dd1">

6. Bind the **clients-maintenance** flow to **clients authentication flow** like this:

<img width="808" alt="image" src="https://github.com/user-attachments/assets/21896d23-0c0d-4622-871f-fa7bf462204a">

7. Try login and issue tokens from http://localhost:8080/realms/mock/protocol/openid-connect/token with the user **maintenance**, from postmant is Ok:

8. Try login and issue tokens from http://localhost:8080/realms/mock/protocol/openid-connect/token with the user **user**, from postmant is Ok **-> But this IS NOT CORRECT because only the maintenance user has the restricted-access role attached** This is the postman request wrong:

<img width="751" alt="image" src="https://github.com/user-attachments/assets/799be45e-c307-49a3-b4bb-239c1c1bebc1">

Any wrong configuration from my side?, the flow created by me is correct? is possible use your extension to restrict issue  tokens for a particular client?, any idea?

### Version

```markdown
- Keycloak: 25.0.2
- This extension: 25.0.1
```

**Comment by masalinas** [comment]
Finally I resolved the error. My problem was the flow it must be bind to direct grant. Afte this correction, I made my end-to-end tests using my users and works ok.

**Comment by sventorben** [comment]
You should double check for flow anyways. You are mixing up required and alternative authenticators on the sample level. That does not make sense as once the required authenticator fails the flow will be terminated and no alternatives executed.
