### ISSUE TITLE
[BUG] Need to relogin after page refresh

### ISSUE THREAD

**Issue by nmanthena18** [sventorben/keycloak-restrict-client-auth#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After all configration done, login to account-console do the page refresh its asking for credentials to relogin.

### Expected Behavior

its should'nt ask for the relogin once login and refresh the page

### Version

```markdown
- Keycloak: 25.0.0
- This extension: 25.0.0
```

**Comment by sventorben** [comment]
Hey @nmanthena18 
could you please provide a screenshot or export of your authentication flows?

**Comment by nmanthena18** [comment]
@sventorben Please find this`{
      "id": "bf0302bf-3c71-4fb5-b74a-3cf3a2e482a8",
      "alias": "Restrict of browser",
      "description": "browser based authentication",
      "providerId": "basic-flow",
      "topLevel": true,
      "builtIn": false,
      "authenticationExecutions": [
        {
          "authenticator": "auth-cookie",
          "authenticatorFlow": false,
          "requirement": "ALTERNATIVE",
          "priority": 0,
          "autheticatorFlow": false,
          "userSetupAllowed": false
        },
        {
          "authenticator": "identity-provider-redirector",
          "authenticatorFlow": false,
          "requirement": "DISABLED",
          "priority": 1,
          "autheticatorFlow": false,
          "userSetupAllowed": false
        },
        {
          "authenticatorFlow": true,
          "requirement": "REQUIRED",
          "priority": 2,
          "autheticatorFlow": true,
          "flowAlias": "Login",
          "userSetupAllowed": false
        },
        {
          "authenticator": "restrict-client-auth-authenticator",
          "authenticatorFlow": false,
          "requirement": "REQUIRED",
          "priority": 3,
          "autheticatorFlow": false,
          "userSetupAllowed": false
        }
      ]
    },`

**Comment by sventorben** [comment]
It looks like you haven't set this up correctly and mixed required and alternative authenticators. Please check https://github.com/sventorben/keycloak-restrict-client-auth/issues/9#issuecomment-937059969 for details or the FAQ at https://github.com/sventorben/keycloak-restrict-client-auth?tab=readme-ov-file#getting-error-kc-services0013-failed-authentication

**Comment by nmanthena18** [comment]
@sventorben that's great, thanks, can you give me quick suggestion for who are all belongs to restricted-access role they should have the access for that client.

**Comment by sventorben** [comment]
No, unfortunately I cannot as this depends on your requirements and can't be answered generically.

**Comment by nmanthena18** [comment]
Certainly, no issues!
