### ISSUE TITLE
[BUG]Redirects do not perform this validation

### ISSUE THREAD

**Issue by wtj1206** [sventorben/keycloak-restrict-client-auth#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Two clients,
Login to the second client using the Identity Provider Redirector direct redirection does not perform permission verification for this plug-in

### Expected Behavior

Open the second application, and the redirect should also start this plug-in

### Version

```markdown
- Keycloak:26.0.1
- This extension:26.0.1
```

**Comment by wtj1206** [comment]
I am sorry that I used 26.0.0 to start the Cookie and Identity Provider Redirector. When I log in to the second client, I can log in automatically. If I log out, I cannot log in to the second client by manually entering the account and password. This means that the login redirect will not execute this plugin, what should I do to ensure that the plugin executes this at any time?  @sventorben

**Comment by sventorben** [comment]
It's highly likely that your flow has not been set up correctly and/or you forgot to configure a post broker login flow.

I would need to see your flows for a better advise.

**Comment by wtj1206** [comment]
{
  "allowRemoteResourceManagement": true,
  "policyEnforcementMode": "ENFORCING",
  "resources": [
    {
      "name": "Default Resource",
      "type": "urn:gitlab:resources:default",
      "ownerManagedAccess": false,
      "attributes": {},
      "uris": [
        "/*"
      ]
    }
  ],
  "policies": [
    {
      "name": "test",
      "description": "",
      "type": "role",
      "logic": "POSITIVE",
      "decisionStrategy": "UNANIMOUS",
      "config": {
        "fetchRoles": "false",
        "roles": "[{\"id\":\"gitlab/restricted-access\",\"required\":true}]"
      }
    },
    {
      "name": "test2",
      "description": "",
      "type": "resource",
      "logic": "POSITIVE",
      "decisionStrategy": "AFFIRMATIVE",
      "config": {
        "resources": "[\"Default Resource\"]",
        "applyPolicies": "[\"test\"]"
      }
    }
  ],
  "scopes": [],
  "decisionStrategy": "UNANIMOUS"
}

**Comment by wtj1206** [comment]
![11](https://github.com/user-attachments/assets/2d8a6e91-96ba-4a45-a7c0-bd0374c49c10)
![22](https://github.com/user-attachments/assets/099a6a6a-0597-44e0-ad56-593a1de12acf)
![33](https://github.com/user-attachments/assets/09b94fae-1116-4b72-8d35-e06569bac236)
![44](https://github.com/user-attachments/assets/e0060681-c95a-485d-9cb6-57b15ae4c6ce)
![55](https://github.com/user-attachments/assets/24870bd9-3175-4a0f-a068-48f23d08725a)
![66](https://github.com/user-attachments/assets/a529338a-f09a-4404-b31a-6d5d7b29a497)
![77](https://github.com/user-attachments/assets/4daded55-d5bf-48bb-9d47-4b75b96f3520)

**Comment by wtj1206** [comment]
Please help check and thank you @sventorben

**Comment by sventorben** [comment]
You cannot simply copy the browser flow and add the authenticator at the end. Please check this picture for a correct implementation:

https://github.com/sventorben/keycloak-restrict-client-auth/blob/main/docs/images/flow_explained.jpg

**Comment by wtj1206** [comment]
Thank you very much for your feedback, the preliminary test has passed. Sorry, I am not familiar with the keycloak process.
