### ISSUE TITLE
[Access Provider] <keycloak-clustered>

### ISSUE THREAD

**Issue by keobr** [sventorben/keycloak-restrict-client-auth#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In a cluster of two nodes does not give a choice access provider (client-role or policy)

### Expected Behavior

choice access provider (client-role or policy)

### Version

```markdown
- Keycloak:15.1.1
- This extension:15.2
```

**Comment by sventorben** [comment]
Hello @keobr,
thanks for reporting this.
Can you please check this is not a duplicate of #24
Regards
Sven-Torben

**Comment by keobr** [comment]
duplicate 
thx
