### ISSUE TITLE
[BUG] Small error in the README

### ISSUE THREAD

**Issue by FlyveHest** [sventorben/keycloak-restrict-client-auth#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When configuring the jar, the README says to use this format

`spi.restrict-client-auth-access-provider.client-role.client-role-name`

But I couldn't get it to work unless I used all hyphens instead of dots.

`spi-restrict-client-auth-access-provider-client-role-client-role-name`

### Version

```markdown
- Keycloak:17.0.1
- This extension: Latest
```

**Comment by sventorben** [comment]
Hello @FlyveHest,

thanks for reporting this. You are absolutely right. Looks like the configuration has changed since the initial proposal.
I will fix it.

Best regards
Sven-Torben
