### ISSUE TITLE
Multiple apps SAML and 18.0.2

### ISSUE THREAD

**Issue by elmidwill** [sventorben/keycloak-restrict-client-auth#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So I got around to trying this today. It doesn't appear to work with SAML authentication on version 18.0.2, or more likely I am not doing something correctly.

After adding the provider, restarting KC, I created a copy of the browser flow, edited it as per instructions. I then created the role in a client, and changed the "Authentication Flow Overrides" to the newly created flow which has the restrict feature enabled. when I try to login from an app using SAML, it redirects to KC and immediately presents me with "Invalid username or password" without prompting for either.

### Version

```markdown
- Keycloak:
- This extension:
```

**Comment by sventorben** [comment]
Hello @elmidwill,

I have this running on several Keycloak instances using SAML. So, I am pretty sure it works with SAML in general. 
Could you please post a screenshot of your authentication flow and relevant client configuration?
Are you trying to use the role-based or policy-based mode?

Regards
Sven-Torben

**Comment by elmidwill** [comment]
Here is the authentication flow
![image](https://user-images.githubusercontent.com/855337/180668052-75645284-58c9-4b6a-937e-fece09c2ab26.png)
I am trying to use role-based mode.

Maybe I am not attaching the flow correctly. I go to clients --> choose a client --> authentication flow overrides --> and change the browser to the new flow with the access restriction in it.

**Comment by sventorben** [comment]
I think that your flow is misconfigured. Keycloak does not allow to combine required and alternative executions on the same level. You should see a corresponding entry in your server logs.
Please take a look at issue #9 for details.

**Comment by elmidwill** [comment]
I'm still quite new to KC, how do I go about creating subflows?

**Comment by elmidwill** [comment]
Thanks. I got it working.
